source 'https://rubygems.org'

gem "rake"
gem "cucumber", "~> 1.3.10"
gem "cucumber-rest-api", '= 0.3'
gem 'cucumber-mailcatcher', '~> 0.12'
gem 'pickle-mongodb', '~> 0.1'
gem 'docker-api', :require => 'docker'
gem 'minke'
