source 'https://rubygems.org'

gem "rake"
gem "cucumber", "~> 1.3.10"
gem "cucumber-rest-api"
gem 'cucumber-mailcatcher', '~> 0.12'
gem 'pickle-mongodb', '~> 0.1'
gem 'docker-api', :require => 'docker'
gem 'consul-ruby-client', '~> 0.0.12'
